[package]
name = "nodns"
version = "0.1.0"
authors = ["mhsjlw <mhsjlw@users.noreply.github.com>"]

[dependencies]
trust-dns = "0.14"
trust-dns-server = "0.14"
rusqlite = "0.13"
tokio-udp = "0.1.1"
dirs = "1.0"
